// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.TestsController.Get~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.ProductsController.GetProductInputNodels~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.ProductViewModel}}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.ProductsController.Upload(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{EPOS.BlazorClient.Shared.ViewModels.ImageUploadResponse}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.ProductsController.GetProductEditModel(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{EPOS.BlazorClient.Shared.ViewModels.ProductViewModel}}")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductController.GenerateBarcode(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductController.GetSelfCode(System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductController.GetSelfCode(System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.InventoriesController.GetInventoryCode(System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.InventoriesController.GetInventoryCode(System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductController.GetSelfProductViewModels~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.SelfedProductViewModel}}")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductsController.GenerateBarcode(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.InventoriesController.GetInventoryViewModels~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.InventoryViewModel}}}")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:EPOS.BlazorClient.Server.Controllers.OrdersController.db")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.InventoriesController.GetInventoryViewModels~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.InventoryViewModel}}}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.InventoriesController.GetProductOptions~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.ProductOption}}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductsController.GetSelfCode(System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductsController.GetSelfCode(System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductsController.GetSelfProductViewModels~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.SelfedProductViewModel}}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.SelfedProductsController.GetSelfProductViewModels~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.SelfedProductViewModel}}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.StocksController.GetStockEntryViewModels~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.StockEntryViewModel}}}")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:EPOS.BlazorClient.Server.Controllers.StocksController.GetStockEntryViewModels~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.IEnumerable{EPOS.BlazorClient.Shared.ViewModels.StockEntryViewModel}}}")]
